---
# tasks file for k8s
- name: Install modules required by containerd
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Copy config to load needed modules on system reboot
  ansible.builtin.copy:
    src: containerd.conf
    dest: /etc/modules-load.d/containerd.conf
    owner: root
    group: root
    mode: "0644"

- name: Setup required sysctl params, these persist across reboots
  ansible.builtin.copy:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    owner: root
    group: root
    mode: "0644"

- name: Reload sysctl
  shell:
    cmd: sysctl --system

- name: Disable swap
  shell: swapoff -a

- name: Disable swap in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Disable selinux now
  shell: setenforce 0
  ignore_errors: yes

- name: Disable SELinux on reboot
  selinux:
    state: disabled

- name: Add docker-ce repository
  ansible.builtin.uri:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: "0644"
    status_code: ["200", "304"]

- name: Install containerd.io
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop:
    - containerd.io
    - conntrack
    - socat

- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Prepare containerd config
  shell: containerd config default | tee /etc/containerd/config.toml

- name: Set containerd systemd cgroup driver 
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    insertafter: '^.*containerd.runtimes.runc.options]$'
    line: '            SystemdCgroup = true'
  notify:
  - Restart containerd

- name: Add DOWNLOAD_DIR to root's .bash_profile for interactive login shell
  ansible.builtin.lineinfile:
    path: /root/.bash_profile
    insertbefore: '^export PATH$'
    line: PATH=$PATH:/usr/local/bin

- name: Add DOWNLOAD_DIR to root's .bashrc for non-interactive login shell
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    insertafter: EOF
    line: PATH=$PATH:/usr/local/bin

- name: Flush handlers
  meta: flush_handlers