---
# handlers file for k8s-master
- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted

- name: Kubelet service
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: kubelet