---
# handlers file for k8s-master
- name: Restart crio
  ansible.builtin.systemd:
    name: crio
    state: started
    enabled: yes

- name: Kubelet service
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: kubelet
