---  
- name: Clean previous initialization
  shell: kubeadm reset -f
  register: cluster_reset

- name: Join kubernetes cluster
  shell: "{{ hostvars['master']['join_command']['stdout'] }}"
  when: cluster_reset is succeeded

- name: Enable kubectl bash completion
  shell: kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/null
