---
# Require kubernetes.core collection
- name: Deploy ArgoCD to K8s cluster
  hosts: master
#  become: yes
#  become_user: root

  tasks:
  - name: Create argocd namespace
    kubernetes.core.k8s:
      api_version: v1
      kind: Namespace
      name: argocd
      state: present
