---
# Require kubernetes.core collection
- name: Deploy ArgoCD to K8s cluster
  hosts: master

  tasks:
  - name: Install kubernetes python package
    ansible.builtin.pip:
      name: kubernetes

  - name: Create argocd namespace
    kubernetes.core.k8s:
      api_version: v1
      kind: Namespace
      name: argocd
      state: present

  - name: Download ArgoCD manifest to the cluster.
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      dest: ~/argo-install.yaml
      mode: '0664'

  - name: Apply ArgoCD manifest to the cluster.
    kubernetes.core.k8s:
      namespace: argocd
      state: present
      src: ~/argo-install.yaml