---
- name: Clean previous initialization
  shell: kubeadm reset -f
  register: cluster_reset

- name: Initialize control-plane
  shell: kubeadm init --pod-network-cidr {{POD_NETWORK_CIDR}} --apiserver-advertise-address {{ APISERVER_ADVERTISE_ADDRESS }}
  when: ansible_processor_cores >= 2 and ansible_memtotal_mb > 1700 and cluster_reset is succeeded

- name: Initialize control-plane with not recommended resources
  shell: kubeadm init --pod-network-cidr {{POD_NETWORK_CIDR}} --apiserver-advertise-address {{ APISERVER_ADVERTISE_ADDRESS }} --ignore-preflight-errors NumCPU,Mem
  when: cluster_reset is succeeded and (ansible_processor_cores < 2 or ansible_memtotal_mb < 1700)

- name: Add KUBECONFIG environment variable to .bashrc and .bash_profile
  lineinfile:
    path: "{{ item }}"
    insertafter: EOF
    line: export KUBECONFIG=/etc/kubernetes/admin.conf
  loop:
    - /root/.bash_profile
    - /root/.bashrc

- name: Install calico network plugin
  shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

- name: Register join command
  shell: kubeadm token create --print-join-command
  register: join_command

- name: Create vagrant user .kube directory
  ansible.builtin.file:
    path: /home/vagrant/.kube/
    state: directory
    owner: vagrant
    group: vagrant
    mode: "0755"

- name: Copy config to vagrant .kube directory
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    remote_src: yes
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
