---
- name: Run role installing kubeadm, kubectl and kubelet on each node
  hosts: k8s
  become: true
  roles:
    - k8s

- name: Initialize control-plane host
  hosts: k8s_master
  become: true
  roles:
    - k8s_master
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin/"
    KUBECONFIG: "/etc/kubernetes/admin.conf"

- name: Initialize worker nodes
  hosts: k8s_workers
  become: true
  roles:
    - k8s_worker
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin/"
    KUBECONFIG: "/etc/kubernetes/admin.conf"