---
- name: Create CNI plugins directory
  ansible.builtin.file:
    path: /opt/cni/bin
    state: directory

- name: Download CNI plugins archive
  ansible.builtin.uri:
    url:  https://github.com/containernetworking/plugins/releases/download/{{CNI_VERSION}}/cni-plugins-linux-{{ARCH}}-{{CNI_VERSION}}.tgz
    dest: /opt/cni/bin/cni-plugins-linux-{{ARCH}}-{{CNI_VERSION}}.tgz

- name: Unarchive downloaded plugins
  ansible.builtin.unarchive:
    src: /opt/cni/bin/cni-plugins-linux-{{ARCH}}-{{CNI_VERSION}}.tgz
    dest: /opt/cni/bin/
    remote_src: yes

- name: Remove CNI plugins archive
  ansible.builtin.file:
    path: /opt/cni/bin/cni-plugins-linux-{{ARCH}}-{{CNI_VERSION}}.tgz
    state: absent

- name: Download crictl archive
  ansible.builtin.uri:
    url:  https://github.com/kubernetes-sigs/cri-tools/releases/download/{{CRICTL_VERSION}}/crictl-{{CRICTL_VERSION}}-linux-{{ARCH}}.tar.gz
    dest: "{{DOWNLOAD_DIR}}/crictl-{{CRICTL_VERSION}}-linux-{{ARCH}}.tar.gz"

- name: Unarchive downloaded crictl archive
  ansible.builtin.unarchive:
    src: "{{DOWNLOAD_DIR}}/crictl-{{CRICTL_VERSION}}-linux-{{ARCH}}.tar.gz"
    dest: "{{DOWNLOAD_DIR}}"
    remote_src: yes
    owner: root
    group: root

- name: Remove crictl archive
  ansible.builtin.file:
    path: "{{DOWNLOAD_DIR}}/crictl-{{CRICTL_VERSION}}-linux-{{ARCH}}.tar.gz"
    state: absent

- name: Download kubeadm, kubectl and kubelet
  ansible.builtin.uri:
    url:  https://storage.googleapis.com/kubernetes-release/release/{{RELEASE}}/bin/linux/{{ARCH}}/{{item}}
    dest: "{{DOWNLOAD_DIR}}/{{item}}"
    owner: root
    group: root
    mode: "0755"
    status_code: ["200", "304"]
  loop:
    - kubeadm
    - kubelet
    - kubectl

- name: Download kubelet service
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/kubernetes/release/{{RELEASE_VERSION}}/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service
    dest: /etc/systemd/system/kubelet.service
    owner: root
    group: root
    mode: "0644"
    status_code: ["200", "304"]

- name: Create kubelet service config directory
  ansible.builtin.file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory

- name: Download kubelet service config
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/kubernetes/release/{{RELEASE_VERSION}}/cmd/kubepkg/templates/latest/deb/kubeadm/10-kubeadm.conf
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    owner: root
    group: root
    mode: "0644"
    status_code: ["200", "304"]

- name: Change ExecStart path in kublet unit file 
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: '^ExecStart=/usr/bin/kubelet'
    line: ExecStart=/usr/local/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS
  loop:
    - /etc/systemd/system/kubelet.service
    - /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  notify:
  - Kubelet service